name: Illumos

on:
  schedule:
    - cron: "0 0 25 * *"
  workflow_dispatch:

jobs:
  gcc:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'zhanhb' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v5

      - name: "Build on VM"
        uses: vmactions/solaris-vm@v1
        with:
          prepare: |
            pkg install gcc make
          run: |
            gmake CC=gcc TARGET=solaris USE_OPENSSL=1 USE_PROMEX=1
