name: NetBSD

on:
  schedule:
    - cron: "0 0 25 * *"
  workflow_dispatch:

jobs:
  gcc:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'zhanhb' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v5

      - name: "Build on VM"
        uses: vmactions/netbsd-vm@v1
        with:
          prepare: |
            /usr/sbin/pkg_add gmake curl
          run: |
            gmake CC=gcc TARGET=netbsd ERR=1 USE_OPENSSL=1 USE_LUA=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_PROMEX=1 USE_ZLIB=1
